
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Tsuru pluginval test release
      run: |
        cd ThirdParty/FRUT
        mkdir build && cd build/
        cmake .. -DCMAKE_INSTALL_PREFIX="../prefix" -DJUCE_ROOT="../../JUCE"
        cmake --build . --target install
        cd ../../..
        mkdir build
        cd build
        cmake .. -G Xcode
        cmake --build . --config Release
        cd ../ThirdParty/pluginval/install
        ./mac_build
        cd ../bin/mac
        unzip pluginval_macOS.zip
        ./pluginval.app/Contents/MacOS/pluginval --strictness-level 10 --validate ../../../../build/Plugin/Release/Tsuru.vst3



